posgradmin/posgradmin/urls.py
from django.urls import path, re_path, include
from django.contrib import admin


from posgradmin.views import (PerfilEditar, PerfilDetail,
                              PerfilAcademicoDetail,
                              PerfilProfesorDetail,
                              PerfilProfesorEditar,
                              AcademicoActividadView,
                              AcademicoResumenCVView,
                              AcademicoPerfilView, InicioView,
                              GradoAcademicoAgregar,
                              GradoAcademicoEliminar,
                              InstitucionAgregarView,
                              AdscripcionEliminar,
                              AdscripcionPCSEliminar,
                              AdscripcionAgregar,
                              AdscripcionPCSAgregar,
                              AsociacionAgregar,
                              AcademicoSortableView, UserDetail,
                              PerfilComite, EstudianteFichaDetail,
                              AcademicoInvitar, AcademicoSearch,
                              TogglePerfilEditar, UploadAssets,
                              CursoIndexView, CursoDetalle,
                              AcademicoFilterView, TutorDetalle,
                              ResumenCurricularView,
                              ResumenCurricularEditView )

from posgradmin.views_academico import \
    EligeAsignatura, SolicitaCurso, PanelConvocatoriaCursos,\
    AcademicoAutocomplete, CursoView, MisCursos, ProponerAsignatura, CursoConstancia, \
    Tutorias

from django.conf.urls.static import static

from posgradmin.settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT, STATIC_URL

urlpatterns = [

    path("__reload__/", include("django_browser_reload.urls")),

    path('admin/upload_assets/', UploadAssets.as_view(), name='upload_assets'),

    re_path(r'^admin/posgradmin/toggle_perfil_editar/', TogglePerfilEditar.as_view(),
        name="toggle_perfil_editar"),

    re_path(r'^admin/posgradmin/academico/invitar/', AcademicoInvitar.as_view(),
        name="academico_invitar"),

    re_path(r'^admin/', admin.site.urls),

    re_path('^accounts/', include('allauth.urls')),

    path('estudiante/<slug:slug>',
        EstudianteFichaDetail.as_view(),
        name='estudiante_ficha'),

    path('export_action/', include("admin_export_action.urls",
                                     namespace="admin_export_action")),

    re_path(r'^institucion/agregar/(?P<devolver>[\w-]+)/',
        InstitucionAgregarView.as_view(),
        name="agregar_institucion"),


    path("inicio/perfil/tutorias/<int:academico_id>/",
         Tutorias.as_view(),
         name="tutorias"),


    re_path(r'^inicio/academico/perfil',
        AcademicoPerfilView.as_view(),
        name="academico_perfil"),

    # re_path(r'^inicio/academico/resumen',
    #     AcademicoResumenCVView.as_view(),
    #     name="academico_resumen"),

    # re_path(r'^inicio/academico/actividad',
    #     AcademicoActividadView.as_view(),
    #     name="academico_actividad"),


    re_path(r'^inicio/perfil/editar$',
        PerfilEditar.as_view(),
        name="editar_perfil"),

    re_path(r'^inicio/perfil/eliminar-grado/(?P<pk>[0-9]+)$',
        GradoAcademicoEliminar.as_view(),
        name="eliminar_grado"),

    path('inicio/perfil/eliminar-adscripcion-pcs/',
         AdscripcionPCSEliminar.as_view(),
         name="eliminar_adscripcion_pcs"),

    re_path(r'^inicio/perfil/eliminar-adscripcion/(?P<pk>[0-9]+)$',
        AdscripcionEliminar.as_view(),
        name="eliminar_adscripcion"),

    re_path(r'^inicio/perfil/agregar-grado$',
        GradoAcademicoAgregar.as_view(),
        name="agregar_grado"),

    re_path(r'^inicio/perfil/agregar-adscripcion$',
        AdscripcionAgregar.as_view(),
        name="agregar_adscripcion"),

    path('inicio/perfil/agregar-adscripcion-pcs',
        AdscripcionPCSAgregar.as_view(),
        name="agregar_adscripcion_pcs"),


    re_path(r'^inicio/perfil/agregar-asociacion$',
        AsociacionAgregar.as_view(),
        name="agregar_asociacion"),

    re_path(r'^inicio/perfil/comite/(?P<username>.+)$',
        PerfilComite.as_view(),
        name="perfilcomite"),

    path(r'inicio/perfil-academico/', PerfilAcademicoDetail.as_view(),
        name='perfil_academico'),

    path('inicio/resumen-curricular/', ResumenCurricularView.as_view(),
         name='resumen_curricular'),

    path('inicio/resumen-curricular/editar/', ResumenCurricularEditView.as_view(),
         name='resumen_curricular_editar'),

    re_path(r'^inicio/perfil-profesor/$',
        PerfilProfesorDetail.as_view(),
        name='perfil_profesor'),

    re_path(r'^inicio/perfil-profesor/editar',
        PerfilProfesorEditar.as_view(),
        name="perfil_profesor_editar"),

    re_path(r'^inicio/academicos/$',
        AcademicoSortableView.as_view(),
        name="lista_academicos"),

    re_path(r'^inicio/academicos/search/$',
        AcademicoSearch.as_view(),
        name="academicos_search"),

    re_path(r'^inicio/perfil/$',
        PerfilDetail.as_view(),
        name='perfil'),

    re_path(r'^inicio/usuario/(?P<pk>[0-9]+)/$',
        UserDetail.as_view(),
        name="user_detail"),

    path('inicio/', InicioView.as_view(), name='inicio'),

    re_path(
        r'^academico-autocomplete/$',
        AcademicoAutocomplete.as_view(),
        name='academico-autocomplete',
        ),


    re_path('^convocatoria-cursos/(?P<pk>[0-9]+)/asignatura/elegir/',
        EligeAsignatura.as_view(),
        name="elige_asignatura"),

    re_path('^convocatoria-cursos/(?P<pk>[0-9]+)/asignatura/(?P<as_id>[0-9]+)/',
        SolicitaCurso.as_view(),
        name="solicita_curso"),

    re_path('^convocatoria-cursos/(?P<pk>[0-9]+)/panel/',
        PanelConvocatoriaCursos.as_view(),
        name="panel_convocatoria_cursos"),

    re_path('^cursos/mis/',
        MisCursos.as_view(),
        name="mis_cursos"),

    re_path('^cursos/(?P<pk>[0-9]+)/constancia/',
        CursoConstancia.as_view(),
        name="curso_constancia"),

    path('cursos/detalle/<int:curso_id>/', CursoDetalle.as_view(),
         name='curso_detalle'),

    re_path('^cursos/(?P<pk>[0-9]+)/',
        CursoView.as_view(),
        name="curso"),

    path('cursos/', CursoIndexView.as_view(),
         name='cursos'),

    path('tutores/<int:academico_id>/', TutorDetalle.as_view(), name='tutor_detalle'),

    path('tutores/linea/<int:linea_id>/', AcademicoFilterView.as_view(), name='tutores_filter_linea'),
    path('tutores/campo/<int:campo_id>/', AcademicoFilterView.as_view(), name='tutores_filter_campo'),
    path('tutores/', AcademicoFilterView.as_view(), name='tutores_filter'),

    # re_path('^proponer-asignatura/',
    #     ProponerAsignatura.as_view(),
    #     name="proponer_asignatura"),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

# ./coordinacion/alimentar_saep.md
# ./coordinacion/oficios_para_firma_de_los_miembros_del_Jurado.md

posgradmin/posgradmin/models.py
import os
import pandas as pd
from pandas.plotting import parallel_coordinates

from collections import defaultdict

import datetime

from django.template.defaultfilters import slugify
from django.db import models
from django.db.models import Q

from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from .settings import MEDIA_URL, \
    APP_PREFIX, MEDIA_ROOT, BASE_DIR

from wordcloud import WordCloud

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from tempfile import NamedTemporaryFile
from django.template.loader import render_to_string
from sh import rm
import subprocess
import pathlib
from pdfrw import PdfReader, PdfWriter, PageMerge


def nota_path(instance, filename):
    (root, ext) = os.path.splitext(filename)
    return os.path.join(u'nota_%s_%s' % (instance.id, slugify(root) + ext))


class Nota(models.Model):
    asunto = models.CharField(max_length=100)
    nota = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User,
                              on_delete=models.CASCADE, null=True, blank=True)

    archivo = models.FileField(upload_to=nota_path,
                               null=True, blank=True)
    estado = models.CharField(max_length=40,
                              default='memo',
                              choices=((u"memo", u"memo"),
                                       (u"solicitud",
                                        u"solicitud"),
                                       ("pendiente", "pendiente"),
                                       ("atendida", "atendida"),
                                       ("cancelada", "cancelada")
                                       ))

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return "%s, fecha: %s" % (self.autor,
                                      self.fecha.strftime("%Y-%m-%d %H:%M"))




class ConvocatoriaCurso(models.Model):
    year = models.PositiveSmallIntegerField("Año")
    semestre = models.PositiveSmallIntegerField(
        choices=((1, 1), (2, 2)))
    status = models.CharField(max_length=10,
            choices=[('abierta', 'abierta'),
                     ('rev CA', 'revisión CA'),
                     ('cerrada', 'cerrada')])

    notas = GenericRelation(Nota,
                           related_query_name='convocatoria_curso')


    def __str__(self):
        if self.status == 'abierta':
            status = '(abierta)'
        else:
            status = ''
        return u"%s-%s %s" % (self.year,
                              self.semestre,
                              status)

    class Meta:
        verbose_name_plural = "Convocatorias para cursos"
        unique_together = ('year', 'semestre')
        ordering = ['year', 'semestre', ]


class Institucion(models.Model):
    nombre = models.CharField("Institución u Organización", max_length=150)
    suborganizacion = models.CharField(
        "Dependencia, Entidad o Departamento", max_length=150)
    pais = models.CharField("País", max_length=100, blank=True)
    estado = models.CharField(max_length=100, blank=True)
    dependencia_UNAM = models.BooleanField(default=False)


    def __str__(self):
        return u"%s, %s" % (self.nombre, self.suborganizacion)

    class Meta:
        verbose_name_plural = "instituciones"
        unique_together = ('nombre', 'suborganizacion', 'estado', 'pais')
        ordering = ['nombre', 'suborganizacion', ]




class EntidadPCS(models.Model):
    nombre = models.CharField("Institución u Organización", max_length=150)
    suborganizacion = models.CharField(
        "Dependencia, Entidad o Departamento", max_length=150)

    def __str__(self):
        return self.suborganizacion

    class Meta:
        verbose_name_plural = "Entidades PCS"
        ordering = ['nombre', 'suborganizacion', ]




class CampoConocimiento(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return u"%s" % self.nombre

    class Meta:
        verbose_name_plural = "campos de conocimiento"


class LineaInvestigacion(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return u"%s" % self.nombre

    class Meta:
        verbose_name_plural = "líneas de investigación"


def headshot_path(instance, filename):
    extension = filename.split('.')[-1]
    return u'headshots/%s.%s' % (instance.user.id, extension)


class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    curp = models.CharField("CURP. Si usted es extranjero(a) y no cuenta con "
                            + "este dato, ingresar la palabra extranjero(a)",
                            max_length=100)
    rfc = models.CharField("RFC. Si usted es extranjero(a) y no cuenta con "
                           + "este dato, ingresar la palabra extranjero(a)",
                           max_length=100)

    CVU = models.CharField(u"Número de CVU",
                           max_length=100, blank=True, null=True)

    telefono = models.CharField(max_length=100)
    telefono_movil = models.CharField(max_length=100, blank=True)

    direccion1 = models.CharField("dirección del lugar de trabajo",
                                  max_length=350)

    codigo_postal = models.PositiveSmallIntegerField(default=0)

    website = models.CharField(max_length=200, blank=True)

    genero = models.CharField(max_length=1, choices=(('M', 'masculino'),
                                                     ('F', 'femenino')))

    nacionalidad = models.CharField(max_length=100)

    fecha_nacimiento = models.DateField('fecha de nacimiento',
                                        blank=True, null=True)

    headshot = models.ImageField("fotografía",
                                 upload_to=headshot_path,
                                 blank=True, null=True)

    notas = GenericRelation(Nota,
                           related_query_name='perfil')


    def __str__(self):
        return u"%s" % self.user.get_full_name()

    def __repr__(self):
        return self.__str__()

    class Meta:
        verbose_name_plural = "Perfiles Personales"
        ordering = ['user__first_name', 'user__last_name', ]


    def adscripcion(self):
        return self.adscripcion_set.order_by('anno_nombramiento').last()


    def adscripcion_ok(self):
        """
        tiene adscripcion o adscripcion pcs
        """

        if self.adscripcion_set.count() > 0:
            return True

        if hasattr(self.user, 'academico'):
            if self.user.academico.adscripcion_pcs:
                return True

        return False


    def perfil_publico_anchor(self):
        return u"""<a href='%sinicio/perfil/publico/%s'>%s</a>""" % (
            APP_PREFIX,
            self.user.get_username(), self.__str__())

    def perfil_comite_anchor(self):
        return u"""<a href='%sinicio/perfil/comite/%s'>🗫</a>""" % (
            APP_PREFIX,
            self.user.get_username())



class Invitado(models.Model):
    nombre = models.CharField(max_length=333)
    correo = models.EmailField(blank=True, null=True)
    descripcion = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Invitados externos"
        verbose_name = "Invitado(a) Externo(a)"

    def __str__(self):
        return self.nombre


class GradoAcademico(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    nivel = models.CharField(max_length=15,
                             choices=(('licenciatura', 'licenciatura'),
                                      ('maestria', 'maestria'),
                                      ('doctorado', 'doctorado')))

    grado_obtenido = models.CharField(max_length=100)

    institucion = models.ForeignKey(Institucion, on_delete=models.CASCADE)

    fecha_obtencion = models.DateField("Fecha de obtención de grado")

    def __str__(self):
        return u"%s @ %s" % (self.grado_obtenido, self.institucion)

    class Meta:
        verbose_name_plural = "Grados académicos"
        ordering = ("-fecha_obtencion",)



estados_estudiante = (
    ('inscrito_maestría', 'inscrito maestría'),
    ('egresado_maestría', 'egresado maestría'),
    ('graduado_maestría', 'graduado maestría'),
    ('graduado_anticipado_maestría', 'graduado anticipado maestría'),
    ('baja_maestría', 'baja maestría'),
    ('suspensión_extraordinaria_maestría', 'suspensión extraordinaria maestría'),
    ('suspensión_1_sem_maestría', 'suspensión 1 sem maestría'),
    ('suspensión_2_sem_maestría', 'suspensión 2 sem maestría'),

    ('inscrito_doctorado', 'inscrito doctorado'),
    ('egresado_doctorado', 'egresado doctorado'),
    ('graduado_doctorado', 'graduado doctorado'),
    ('graduado_anticipado_doctorado', 'graduado anticipado doctorado'),
    ('baja_doctorado', 'baja doctorado'),
    ('suspensión_extraordinaria_doctorado', 'suspensión extraordinaria doctorado'),
    ('suspensión_1_sem_doctorado', 'suspensión 1 sem doctorado'),
    ('suspensión_2_sem_doctorado', 'suspensión 2 sem doctorado'),

    ('movilidad', 'movilidad'),
    ('indeterminado', 'indeterminado'),
    ('anómalo', 'anómalo'),
)


class Estudiante(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cuenta = models.CharField(max_length=100)

    estado = models.CharField(
        max_length=40,
        choices=estados_estudiante,
        null=True, blank=True)

    plan = models.CharField(
        max_length=20,
        choices=[("Maestría", "Maestría"),
                 ("Doctorado", "Doctorado")],
        default="Maestría"
    )

posgradmin/posgradmin/templates/posgradmin/cursos_index.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load markdownify %}

{% block title %}
Cursos y horarios
{% endblock %}


{% block content %}



<h1>Cursos y horarios</h1>
<div class="max-w-prose text-base">
<h3>Semestre 2025-2</h3>



<p>El semestre 2025-2 comprende del 27 de enero al 23 de mayo de 2025.</p>

<p>
Las ligas para las sesiones virtuales de los cursos que se impartirán en línea se deben solicitar directamente a la(o)s profesora(e)s de cada curso, enviando un mensaje al correo registrado. 
</p>
<p>
El registro a los cursos intersemestrales se debe realizar antes del inicio del curso, directamente al correo de la(o)s profesora(e)s, con copia a sostenibilidad@posgrado.unam.mx. Dichos cursos se deben inscribir en el sistema de SIAEP en el periodo de inscripción al semestre 2025-2.
</p>
<p>
Esta página se actualiza constantemente, sugerimos revisarla con
frecuencia.
</p>



{{ cursos_md|markdownify }}



<div class="bg-gray-100 p-2">
<h1>Sesiones de tutoría</h1>

<ul>
<li><a href="/cursos/sesiones_de_tutoria_i/">Sesiones de tutoría I Obligatoria para alumnos del segundo semestre de la Maestría</a></li>
<li><a href="/cursos/sesiones_de_tutoria_ii/">Sesiones de tutoría II Obligatoria para alumnos del tercer semestre de la Maestría</a></li>
<li><a href="/cursos/actividades_para_la_obtencion_del_grado/">Actividades para la obtención del grado_Obligatoria para alumnos del cuarto semestre de la Maestría</a></li>
</ul>

<h1>Seminarios de tesis</h1>

Sólo se podrán registrar con autorización previa del Comité Académico.
<ul>
<li><a href="/cursos/temas_selectos_i_seminario_de_tesis_i/">Temas Selectos I Seminario de Tesis I</a></li>
<li><a href="/cursos/temas_selectos_ii_seminario_de_tesis_ii/">Temas Selectos II Seminario de Tesis II</a></li>
</ul>


<h1>Seminarios de Investigación</h1>

Sólo se podrán registrar con autorización previa del Comité Académico.
<ul>
<li><a href="/cursos/temas_selectos_i_seminario_de_investigacion_i/">Temas Selectos I Seminario de Investigación I</a></li>
<li><a href="/cursos/temas_selectos_ii_seminario_de_investigacion_ii/">Temas Selectos II Seminario de Investigación II</a></li>
<li><a href="/cursos/temas_selectos_iii_seminario_de_investigacion_iii/">Temas Selectos III Seminario de Investigación III</a></li>
</ul>
</div>
{% endblock %}

posgradmin/posgradmin/templates/posgradmin/grado_academico_agregar.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>{{ user.get_full_name }}</h1>

<hr>
<br />

{% crispy form %}


<script>
$(document).ready(function() {
    $('.dateinput').datepicker({ dateFormat: 'yy-mm-dd'});
}); 
</script>

{% endblock %}

posgradmin/posgradmin/templates/posgradmin/institucion_agregar.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
   {% crispy form %}
{% endblock %}

posgradmin/posgradmin/templates/posgradmin/perfil_personal_comite.html
<div class="flex flex-wrap">
  

  
  <div class="bg-neutral-100
	      p-4">
    
    <h3>Datos Personales</h3>
    
    {% if U.perfil.headshot %}
    <img alt="foto" class=""
	 width="150px"
	 src="{{ U.perfil.headshot.url }}" />
    
    {% endif %}

    <div class="grid grid-cols-2 gap-2">
      <div class="justify-self-end"><strong>Fecha de Nacimiento</strong></div>
      <div>{{ U.perfil.fecha_nacimiento|default:"" }}</div>
      
      <div class="justify-self-end"><strong>Genero</strong></div>
      <div>{{ U.perfil.genero }}</div>
      
      <div class="justify-self-end"><strong>Nacionalidad</strong></div>
      <div>{{ U.perfil.nacionalidad }}</div>
      
      <div class="justify-self-end"><strong>CURP</strong></div>
      <div>{{ U.perfil.curp }}</div>
      
      <div class="justify-self-end"><strong>RFC</strong></div>
      <div>{{ U.perfil.rfc }}</div>
    </div>
  </div>



  <div class="bg-green-50
	      max-w-prose
	      p-4">
    
    <h3>
      Información de contacto
    </h3>
    <div class="grid grid-cols-2 gap-2">
      
      <div class="justify-self-end"><strong>Teléfono</strong></div>
      <div>{{ U.perfil.telefono }}</div>
    
      <div class="justify-self-end"><strong>Teléfono Móvil</strong></div>
      <div>{{ U.perfil.telefono_movil }}</div>
    
      <div class="justify-self-end"><strong>email</strong></div>
      <div><a href="mailto:{{ U.email }}">{{ U.email }}</a></div>
    
      <div class="justify-self-end"><strong>Sitio Web</strong></div>
      <div>{{ U.perfil.website }}</div>
    
      <div class="justify-self-end"><strong>Dirección</Strong></div>
      <div>{{ U.perfil.direccion1 }}</div>
    
      <div class="justify-self-end"><strong>Código Postal</strong></div>
      <div>{{ U.perfil.codigo_postal|default:"" }}</div>
    </div>
  </div>


  
  <div class="bg-amber-50
	      p-4">

    <h3>
      Adscripción
    </h3>

    <ul>
      {% if U.academico.adscripcion_pcs %}
      <li>
	<strong>{{ U.academico.adscripcion_pcs }}</strong>
      </li>
      {% endif %}
      
      {% for ad in U.perfil.adscripcion_set.all %}
      <li class="list-group-item">
	{{ ad }}
	{% if ad.catedra_conacyt %}
	<br />
	Cátedra CONACYT
	{% endif %}
	<br />
	{% if not ad.asociacion_PCS %}
	{{ ad.nombramiento }} desde {{ ad.anno_nombramiento }}
	{% endif %}
      </li>
      {% endfor %}
    </ul>
  </div>


  <div class="flex flex-col
	      p-4
	      bg-blue-50">
    
    <h3>
      Grados Académicos
    </h3>
      
    {% for grado in U.gradoacademico_set.all %}
    <div>
      <strong>{{ grado.grado_obtenido }} </strong>@ {{ grado.institucion }}
      <p class="list-group-item-text">
	nivel {{ grado.nivel }}
	obtenido el {{ grado.fecha_obtencion }}<br />
      </p>
    </div>
    {% empty %}
    
    {% endfor %}
  </div>
</div>

posgradmin/posgradmin/templates/posgradmin/posgradmin_base.html
{% extends "base.html" %}
{% load admin_urls %}


{% block title %}{% endblock %}

{% block extrahead %}

{% endblock %}




{% block usertools %}

{% endblock %}


{% block breadcrumbs %}
<div class="breadcrumbs">
  {% for crumb in breadcrumbs %}
  &rsaquo; <a href="{{ crumb.0 }}">{{ crumb.1 }}</a>
  {% endfor %}
</div>
{% endblock %}

{% block messages %}{% endblock %}

{% block pretitle %}{% endblock %}

{% block content %}
{% endblock %}

{% block object-tools %}{% endblock %}

{% block sidebar %}{% endblock %}
{% block footer %}{% endblock %}

posgradmin/posgradmin/templates/posgradmin/tutor_detail.html
{% extends "posgradmin/posgradmin_base.html" %}
{% load markdownify %}

{% block title %}
{{ a }}
{% endblock %}


{% block content %}
<h1>{{ a }}</h1>

<div class="flex flex-col bg-teal-50 p-2">
  <div class="w-max-prose">
    <div>Acreditación: {{ a.show_acreditacion }} </div>

    {% if a.acreditacion == "M" or a.acreditacion == "D" %}
    {% if a.disponible_tutor and a.disponible_tutor_vobo %}
    <div> Disponible como tutor principal (dirección de alumnos).</div>
    {% else %}
    <div> Sin disponibilidad para tutor principal.</div>
    {% endif %}

    
    {% if a.disponible_miembro and a.disponible_miembro_vobo %}
    <div> Disponible como miembro de comité tutor (asesoría de alumnos).</div>
    {% else %}
    <div> Sin disponibilidad para miembro de comité tutor (asesoría de alumnos).</div>
    {% endif %}
    
    
    {% else %}
    
    {% if a.acreditacion == "MCT_M" %}
    {% if a.disponible_miembro and a.disponible_miembro_vobo %}
    <div> Disponible como miembro de comité tutor (asesoría de alumnos).</div>
    {% endif %}
    
    {% endif %}
    
    {% endif %}
    
    
    <h2> Información de contacto</h2>
    
    <a href="mailto:{{ a.user.email }}">{{ a.user.email }}</a>
    <br />
    {% if a.user.perfil.website %}
    <a href="{{ a.user.perfil.website }}">
      {{ a.user.perfil.website|urlize }}
    </a>
    {% endif %}
    
    
    
    <h2> Adscripción</h2>

    <ul>
      {% if a.adscripcion_pcs %}
      <li>{{ a.adscripcion_pcs }}</li>
      {% endif %}
      {% for ad in a.user.perfil.adscripcion_set.all %}
      <li> {{ ad }} {% if ad.catedra_conacyt %}Cátedra CONACYT{% endif %}</li>
      {% endfor %}
    </ul>
      
  </div>

  <div class="bg-white p-2 w-">
    <img class="w-1/2 float-right" src="https://sostenibilidad.posgrado.unam.mx/media/perfil-academico/{{ a.id }}/wordcloud.png" />        
    <h1> Perfil académico</h1>
    
    <h2> Grados académicos</h2>
    
    <ul>
      {% for grado in a.user.gradoacademico_set.all %}
      <li>{{ grado.grado_obtenido }}, {{ grado.institucion }}, nivel {{ grado.nivel }} obtenido el {{ grado.fecha_obtencion }}</li>
      {% endfor %}
    </ul>
    
    
    <h2> Temas de Interés</h2>
    
    {{ a.lineas }}
    
    <h2> Palabras clave</h2>
    
    <ul>
      {% for p in palabras_clave %}
      <li> {{ p }}</li>
      {% endfor %}
    </ul>
    
    <h2> Cinco publicaciones más destacadas en temas relacionados con las Ciencias de la Sostenibilidad</h2>
    
    {{ a.top_5|linebreaksbr }}
    
    
    <h1> Principales proyectos relacionados con Ciencias de la Sostenibilidad durante los últimos cinco años</h1>
    
    {{ a.proyectos_sostenibilidad|linebreaksbr }}
    
    <h1> Proyectos vigentes en los que pueden participar alumnos del PCS</h1>
    
    {{ a.proyectos_vigentes|linebreaksbr }}
    
    {% if a.acreditacion == 'D' %}
    <h2> Líneas de Investigación</h2>
    
    <ul>
      {% for l in a.lineas_de_investigacion.all %}
      <li> {{ l }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    
    
    <h2> Campos de Conocimiento</h2>
    <ul>
      {% for c in a.campos_de_conocimiento.all %}
      <li>{{ c }}</li>
      {% endfor %}
    </ul>
  </div>

</div>
{% endblock %}

  